# Generated by Django 5.0 on 2024-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_category_listing_image_alter_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
